export const hyderabadLocalities: { name: string; routeNumber: string }[] = [
  { name: 'Mehdipatnam', routeNumber: '01' },
  { name: 'Lakdikapul', routeNumber: '02' },
  { name: 'Begumpet', routeNumber: '03' },
  { name: 'Ameerpet', routeNumber: '04' },
  { name: 'Kukatpally', routeNumber: '05' },
  { name: 'Dilsukhnagar', routeNumber: '06' },
  { name: 'Uppal', routeNumber: '07' },
  { name: 'LB Nagar', routeNumber: '08' },
  { name: 'Secunderabad', routeNumber: '09' },
  { name: 'Malkajgiri', routeNumber: '10' },
  { name: 'Nampally', routeNumber: '11' },
  { name: 'Charminar', routeNumber: '12' },
  { name: 'Tolichowki', routeNumber: '13' },
  { name: 'Attapur', routeNumber: '14' },
  { name: 'Miyapur', routeNumber: '15' },
  { name: 'Hitech City', routeNumber: '16' },
  { name: 'Gachibowli', routeNumber: '17' },
  { name: 'Panjagutta', routeNumber: '18' },
  { name: 'Tarnaka', routeNumber: '19' },
  { name: 'Alwal', routeNumber: '20' },
  { name: 'ECIL', routeNumber: '21' },
  { name: 'Koti', routeNumber: '22' },
  { name: 'Abids', routeNumber: '23' },
  { name: 'Narayanguda', routeNumber: '24' },
  { name: 'Falaknuma', routeNumber: '25' },
  { name: 'Moinabad', routeNumber: '26' },
  { name: 'Narsingi', routeNumber: '27' },
  { name: 'Kondapur', routeNumber: '28' },
  { name: 'Lingampally', routeNumber: '29' },
  { name: 'Banjara Hills', routeNumber: '30' },
  { name: 'Jubilee Hills', routeNumber: '31' },
];
