export const routes = [
    { routeNo: '01', routeName: 'Mehdipatnam ' },
    { routeNo: '02', routeName: 'lakdikapul' },
    { routeNo: '03', routeName: 'Begumpet' },
    { routeNo: '04', routeName: 'Ameerpet' },
    { routeNo: '05', routeName: 'Kukatpally' },
    { routeNo: '06', routeName: 'Dilsukhnagar' },
    { routeNo: '07', routeName: 'Uppal' },
    { routeNo: '08', routeName: 'LB Nagar' },
    { routeNo: '09', routeName: 'secunderabad' },
    { routeNo: '10', routeName: 'malkajgiri' },
    { routeNo: '11', routeName: 'Nampally' },
    { routeNo: '12', routeName: 'Charminar'},
    { routeNo: '13', routeName: 'Tolichowki'},
    { routeNo: '14', routeName: 'Attapur'},
    { routeNo: '15', routeName: 'Miyapur'},
    { routeNo: '16', routeName: 'Hitech City'},
    { routeNo: '17', routeName: 'Gachibowli'},
    { routeNo: '18', routeName: 'Panjagutta'},
    { routeNo: '19', routeName: 'Tarnaka'},
    { routeNo: '20', routeName: 'Alwal'},
    { routeNo: '21', routeName: 'ECIL'},
    { routeNo: '22', routeName: 'Koti'},
    { routeNo: '23', routeName: 'Abids'},
    { routeNo: '24', routeName: 'Narayanguda'},
    { routeNo: '25', routeName: 'Falaknuma'},
    { routeNo: '26', routeName: 'Moinabad'},
    { routeNo: '27', routeName: 'Narsingi'},
    { routeNo: '28', routeName: 'Kondapur'},
    { routeNo: '29', routeName: 'Lingampally'},
    { routeNo: '30', routeName: 'Banjara Hills'},
    { routeNo: '31', routeName: 'Jubilee Hills'},
]